import type { Metadata } from "next";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { DrawerDemo } from "@/components/cookies-agreement-dialogue";
import MainNav from "@/components/main-nav";
import { MainFooter } from "@/components/main-footer";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Font Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth focus:scroll-auto"
      suppressHydrationWarning
    >
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex w-full flex-col",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <MainNav />
          <main className="flex min-h-screen flex-col items-center justify-between px-6 sm:px-36 py-12">
            {children}
          </main>
          <MainFooter />
          <DrawerDemo />
        </ThemeProvider>
      </body>
    </html>
  );
}
